### PR TITLE
WIP: Improve documentation, Fix issue with Apache not wanting to run as root

### PR DESCRIPTION
**Pull request by silbinarywolf**
- Improve documentation
- Fix issue with Apache not wanting to run as root

More to be added as I go

### CODE REVIEW

**Comment by nyeholt** [comment]
So - should the solr support be instead left as a separate container?

**Comment by silbinarywolf** [comment]
I thought so, but since we're running the "start.jar" in the actual Solr module, it makes sense to just put it on the same container IMO.

**Comment by silbinarywolf** [comment]
@nyeholt ^

**Comment by nyeholt** [comment]
Oh right - take WIP out of the subject line if it's ready :P 

On the java front - I think I want to break this dockerfile up into a couple of smaller ones so for now I'll allow it, and remove it when it gets broken up later.

**Pull request merged**
